import mysql from "mysql2/promise";
import { randomUUID } from "crypto";

const globalForDb = global as unknown as { pool?: mysql.Pool };
export const pool = globalForDb.pool ?? mysql.createPool(process.env.DATABASE_URL || "");
if (process.env.NODE_ENV !== "production") globalForDb.pool = pool;

async function one<T=any>(sql:string, params:any[]=[]):Promise<T|null>{const [rows]=await pool.query(sql,params);return (rows as T[])[0]||null}
async function many<T=any>(sql:string,params:any[]=[]):Promise<T[]>{const [rows]=await pool.query(sql,params);return rows as T[]}
async function run(sql:string,params:any[]=[]){return pool.execute(sql,params)}
function level(row:any){return row&&{...row,isActive:!!row.isActive}}
function category(row:any){return row&&{...row,selected:!!row.selected,prefixFilterEnabled:!!row.prefixFilterEnabled,products:typeof row.products==='string'?JSON.parse(row.products):row.products}}
function schedule(row:any){return row&&{...row,enabled:!!row.enabled}}
function settings(row:any){return row&&{...row,scheduleEnabled:!!row.scheduleEnabled}}
function fields(data:Record<string,any>){const keys=Object.keys(data);return {sql:keys.map(k=>`\`${k}\` = ?`).join(', '),values:keys.map(k=>data[k] instanceof Date?data[k]:typeof data[k]==='object'&&data[k]!==null?JSON.stringify(data[k]):data[k])}}

export const db={
  user:{findUnique:async({where:{username,id}}:any)=>one(`SELECT * FROM \`User\` WHERE ${username?'username':'id'} = ?`,[username||id])},
  settings:{findUnique:async(_:any={})=>settings(await one('SELECT * FROM `Settings` WHERE id=1')),upsert:async({update,create}:any)=>{const old=await one('SELECT id FROM `Settings` WHERE id=1');const data=old?update:create;if(old&&Object.keys(data).length){const f=fields(data);await run(`UPDATE \`Settings\` SET ${f.sql} WHERE id=1`,f.values)}else if(!old){const f=fields({id:1,...data});await run(`INSERT INTO \`Settings\` (${Object.keys({id:1,...data}).map(x=>'`'+x+'`').join(',')}) VALUES (${Object.keys({id:1,...data}).map(()=>'?').join(',')})`,f.values)}return settings(await one('SELECT * FROM `Settings` WHERE id=1'))},update:async({data}:any)=>{const f=fields(data);await run(`UPDATE \`Settings\` SET ${f.sql} WHERE id=1`,f.values);return settings(await one('SELECT * FROM `Settings` WHERE id=1'))}},
  priceLevel:{findMany:async(_:any={})=> (await many('SELECT * FROM `PriceLevel` ORDER BY createdAt ASC')).map(level),findFirst:async(_:any={})=>level(await one('SELECT * FROM `PriceLevel` ORDER BY createdAt ASC LIMIT 1')),findUnique:async({where:{id}}:any)=>level(await one('SELECT * FROM `PriceLevel` WHERE id=?',[id])),count:async()=>Number((await one<any>('SELECT COUNT(*) AS count FROM `PriceLevel`'))?.count||0),create:async({data}:any)=>{const id=randomUUID();await run('INSERT INTO `PriceLevel` (id,name,isActive,apiKey,createdAt) VALUES (?,?,0,?,NOW())',[id,data.name,data.apiKey||null]);return level(await one('SELECT * FROM `PriceLevel` WHERE id=?',[id]))},update:async({where:{id},data}:any)=>{const f=fields(data);await run(`UPDATE \`PriceLevel\` SET ${f.sql} WHERE id=?`,[...f.values,id]);return level(await one('SELECT * FROM `PriceLevel` WHERE id=?',[id]))},delete:async({where:{id}}:any)=>run('DELETE FROM `PriceLevel` WHERE id=?',[id])},
  productCategory:{findMany:async({where={},select}:any={})=>{const clauses:string[]=[];const values:any[]=[];for(const [k,v] of Object.entries(where)){clauses.push(`\`${k}\`=?`);values.push(v)}const cols=select?Object.keys(select).map(k=>'`'+k+'`').join(','):'*';return (await many(`SELECT ${cols} FROM \`ProductCategory\`${clauses.length?' WHERE '+clauses.join(' AND '):''} ORDER BY title ASC`,values)).map(category)},findUnique:async({where:{id}}:any)=>category(await one('SELECT * FROM `ProductCategory` WHERE id=?',[id])),update:async({where:{id},data}:any)=>{const f=fields(data);await run(`UPDATE \`ProductCategory\` SET ${f.sql} WHERE id=?`,[...f.values,id])},deleteMany:async({where:{levelId}}:any)=>run('DELETE FROM `ProductCategory` WHERE levelId=?',[levelId]),upsert:async({where:{levelId_title},update,create}:any)=>{const old=await one<any>('SELECT id FROM `ProductCategory` WHERE levelId=? AND title=?',[levelId_title.levelId,levelId_title.title]);const data=old?update:create;if(old){const f=fields(data);await run(`UPDATE \`ProductCategory\` SET ${f.sql} WHERE id=?`,[...f.values,old.id])}else{const id=randomUUID(),payload={id,...data};const f=fields(payload);await run(`INSERT INTO \`ProductCategory\` (${Object.keys(payload).map(k=>'`'+k+'`').join(',')}) VALUES (${Object.keys(payload).map(()=>'?').join(',')})`,f.values)}}},
  broadcastSchedule:{findMany:async(_:any={})=> (await many('SELECT * FROM `BroadcastSchedule` ORDER BY createdAt DESC')).map(schedule),create:async({data}:any)=>{const id=randomUUID();await run('INSERT INTO `BroadcastSchedule` (id,name,enabled,days,time,categoryIds,createdAt) VALUES (?,?,?,?,?,?,NOW())',[id,data.name,!!data.enabled,data.days,data.time,data.categoryIds])},update:async({where:{id},data}:any)=>{const f=fields(data);await run(`UPDATE \`BroadcastSchedule\` SET ${f.sql} WHERE id=?`,[...f.values,id])},delete:async({where:{id}}:any)=>run('DELETE FROM `BroadcastSchedule` WHERE id=?',[id])},
  activityLog:{findMany:async({take=100}:any={})=>await many('SELECT * FROM `ActivityLog` ORDER BY createdAt DESC LIMIT ?',[take]),create:async({data}:any)=>{const id=randomUUID();await run('INSERT INTO `ActivityLog` (id,type,message,meta,createdAt) VALUES (?,?,?,?,NOW())',[id,data.type,data.message,data.meta?JSON.stringify(data.meta):null])}}
};
