import bcrypt from "bcryptjs";
import { pool, db } from "../lib/mysql";
async function main(){
  await pool.query(`CREATE TABLE IF NOT EXISTS \`User\` (id VARCHAR(191) PRIMARY KEY, username VARCHAR(191) UNIQUE NOT NULL, passwordHash VARCHAR(255) NOT NULL, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)`);
  await pool.query(`CREATE TABLE IF NOT EXISTS \`Settings\` (id INT PRIMARY KEY, siteUrl VARCHAR(500), apiKey TEXT, selectedLevelId VARCHAR(50), theme VARCHAR(10) DEFAULT 'light', scheduleEnabled BOOLEAN DEFAULT TRUE, botToken TEXT, targetChatId VARCHAR(150), pollingInterval INT DEFAULT 15, caption TEXT, broadcastFormat VARCHAR(10) DEFAULT 'image', headerTitle VARCHAR(255) DEFAULT 'PRICE UPDATE', headerSubtitle VARCHAR(255) DEFAULT 'Harga terbaru hari ini', primaryColor VARCHAR(20) DEFAULT '#5B5BD6', accentColor VARCHAR(20) DEFAULT '#A78BFA', headerImageUrl VARCHAR(1000), updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`);
  await pool.query(`CREATE TABLE IF NOT EXISTS \`PriceLevel\` (id VARCHAR(191) PRIMARY KEY, name VARCHAR(100) NOT NULL, isActive BOOLEAN DEFAULT FALSE, apiKey TEXT, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)`);
  await pool.query(`CREATE TABLE IF NOT EXISTS \`ProductCategory\` (id VARCHAR(191) PRIMARY KEY, levelId VARCHAR(191) NOT NULL, title VARCHAR(255) NOT NULL, type VARCHAR(100), selected BOOLEAN DEFAULT FALSE, prefixFilterEnabled BOOLEAN DEFAULT FALSE, excludedPrefixes TEXT, productCount INT DEFAULT 0, products JSON NOT NULL, syncedAt DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY level_title(levelId,title))`);
  await pool.query(`CREATE TABLE IF NOT EXISTS \`BroadcastSchedule\` (id VARCHAR(191) PRIMARY KEY, name VARCHAR(100) NOT NULL, enabled BOOLEAN DEFAULT FALSE, days VARCHAR(100) NOT NULL, time VARCHAR(5) NOT NULL, categoryIds TEXT NOT NULL, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)`);
  await pool.query(`CREATE TABLE IF NOT EXISTS \`ActivityLog\` (id VARCHAR(191) PRIMARY KEY, type VARCHAR(40) NOT NULL, message TEXT NOT NULL, meta JSON, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)`);
  const user=await db.user.findUnique({where:{username:'admin'}});if(!user){const {randomUUID}=await import('crypto');await pool.execute('INSERT INTO `User` (id,username,passwordHash,createdAt) VALUES (?,?,?,NOW())',[randomUUID(),'admin',await bcrypt.hash('admin123',12)])}await db.settings.upsert({update:{},create:{id:1}});if(await db.priceLevel.count()===0){await db.priceLevel.create({data:{name:'Member'}});await db.priceLevel.create({data:{name:'H2H'}})}const settings=await db.settings.findUnique();if(!settings?.selectedLevelId){const first=await db.priceLevel.findFirst();if(first)await db.settings.update({data:{selectedLevelId:first.id}})}
}
main().then(()=>pool.end()).catch(async e=>{console.error(e);await pool.end();process.exit(1)});
